@startuml Diagrama de Componentes
package "Frontend" {
  [App Web] --> [API Backend]
}

package "Backend" {
  [API Backend] --> [AuthService]
  [API Backend] --> [EmailService]
  [API Backend] --> [TransacaoService]
  [API Backend] --> [VantagemService]
  [API Backend] --> [CupomService]
}

package "Database" {
  [Banco de Dados]
}

[TransacaoService] --> [Banco de Dados]
[VantagemService] --> [Banco de Dados]
[CupomService] --> [Banco de Dados]
@enduml