@startuml listar vantagens
participant EmpresaParceira as Empresa
participant "Frontend" as Front
participant "VantagemController" as Controller
participant "VantagemService" as Service
participant "VantagemDAO" as DAO
participant "Banco de Dados" as DB

Empresa -> Front : Solicita listagem de vantagens
Front -> Controller : GET /vantagens
Controller -> Service : List<Vantagem> findAll()
Service -> DAO : findAll()
DAO -> DB : SELECT * FROM vantagens
DB --> DAO : Lista de vantagens
DAO --> Service : Lista de vantagens
Service --> Controller : Lista de vantagens
Controller --> Front : HTTP 200 OK + JSON (vantagens)
Front -> Empresa : Exibe lista de vantagens

@enduml