@startuml Diagrama de Comunicação - Compra de Vantagens (Aluno)
skinparam handwritten false
skinparam style strictuml
skinparam linetype ortho ' Estilo de linha reta para melhor clareza nas conexões diretas

actor Aluno as aluno

rectangle "AlunoController" as ac
rectangle "VantagemService" as vs
rectangle "UsuarioService" as us
rectangle "AlunoDAO" as adao
rectangle "VantagemDAO" as vdao
rectangle "TransacaoDAO" as tdao
rectangle "Banco de Dados" as db 

aluno -> ac : 1: GET /confirmar-compra/{id}
ac -> vs : 2: buscarVantagemPorId(id)
vs -> vdao : 3: findById()
vdao -> db : 4: SELECT Vantagem

aluno -> ac : 6: POST /comprar-vantagem (id)
ac -> vs : 7: comprarVantagem(aluno, vantagem)
vs -> adao : 8: save(aluno)
adao -> db : 9: UPDATE Aluno
vs -> vdao : 10: save(vantagem)
vdao -> db : 11: UPDATE Vantagem
vs -> tdao : 12: save(transacao)
tdao -> db : 13: INSERT Transacao
@enduml
