@startuml Diagrama de Comunicação - Consultas de Extrato (Professor e Aluno)
skinparam handwritten false
skinparam style strictuml
skinparam linetype ortho ' Estilo de linha reta para melhor clareza nas conexões diretas

actor Aluno as aluno
actor Professor as professor

rectangle "AlunoController" as ac
rectangle "ProfessorController" as pc
rectangle "UsuarioService" as us
rectangle "TransacaoDAO" as tdao
rectangle "Banco de Dados" as db

aluno -> ac : 1: GET /home/aluno/extrato
ac -> us : 2: getExtratoAluno(aluno)
us -> tdao : 3: findByAlunoDestinoOrderByDataTransacaoDesc(aluno)
tdao -> db : 4: SELECT Transacoes

professor -> pc : 5: GET /home/professor/extrato
pc -> us : 6: getExtratoProfessor(prof)
us -> tdao : 7: findByProfessorOrigemOrderByDataTransacaoDesc(professor)
tdao -> db : 8: SELECT Transacoes
@enduml
