@startuml Sistema de troca
' Diagrama de Casos de Uso
left to right direction
actor Aluno
actor Professor
actor EmpresaParceira
actor Usuario
actor Sistema

Usuario <|-- Aluno
Usuario <|-- Professor
Usuario <|-- EmpresaParceira

(Notificar aluno por email) --> Aluno
(Distribuir moedas) --> Aluno
(Escrever mensagem de reconhecimento) --> Aluno
Aluno --> (Cadastrar-se no sistema)
Aluno --> (Consultar extrato)
Aluno --> (Trocar moedas por vantagens)

Professor --> (Distribuir moedas)
Professor --> (Consultar extrato)
Professor --> (Escrever mensagem de reconhecimento)

Usuario --> (Fazer login no sistema)

(Enviar email ao parceiro) --> EmpresaParceira
(Trocar moedas por vantagens) --> EmpresaParceira
EmpresaParceira --> (Cadastrar-se no sistema)
EmpresaParceira --> (Cadastrar vantagens)

Sistema --> (Notificar aluno por email)
Sistema --> (Enviar email ao parceiro)
@enduml