@startuml Diagrama de Comunicação - Listagem de Vantagens (Aluno - Disponíveis)

skinparam handwritten false
skinparam style strictuml
skinparam linetype ortho ' Estilo de linha reta para melhor clareza nas conexões diretas

actor Aluno as aluno

rectangle "AlunoController" as ac
rectangle "UsuarioService" as us
rectangle "VantagemService" as vs
rectangle "AlunoDAO" as adao
rectangle "VantagemDAO" as vdao
rectangle "Banco de Dados" as db  

aluno -> ac : 1: GET /home/aluno
ac -> us : 2: findAlunoById()
us -> adao : 3: findById()
adao -> db : 4: SELECT Aluno
ac -> vs : 5: listarTodasVantagens()
vs -> vdao : 6: findByVendidaFalseAndAlunoCompradorIsNull()
vdao -> db : 7: SELECT Vantagens
@enduml
